alias .1='cd ..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias rm='rm -i'
alias mv='mv -i'
alias cp='/bin/cp -i --preserve=timestamps'
alias df='/bin/df -hTP'
alias du='/usr/bin/du -hx --max-depth=1'
alias ll='/bin/ls -lh --color=auto --time-style=long-iso 2>/dev/null'
alias lt='/bin/ls -lhtr --color=auto --time-style=long-iso 2>/dev/null'
alias lynx='lynx -accept_all_cookies'
alias mysql='mysql --default-character-set=utf8'
alias less='less -R'
alias tless='less -R `ls -tr1|tail -1`'
alias ttail='tail -f `ls -tr1|tail -1`'
alias tailf='tail -f'
alias grep='grep --color=always'
alias rlf='readlink -f'
alias tree='tree -N'
alias stl='systemctl'
alias stlu='systemctl start'
alias stld='systemctl stop'
alias stlr='systemctl restart'
alias stlrl='systemctl reload'
alias stlst='systemctl status'
alias stll='systemctl list-unit-files'

