#!/bin/bash
# https://github.com/Panblack/ezdpl
# Last update: 2017-04-03

funUsage() {
    echo -e "Usage: ./ezdpl <ip address>:[port] <ServerType/Operation> [reboot Y|N(N)] [username(root)]\nServerType/Operation:"
    cd servers; for x in * ; do cd $x; for y in *; do echo $x/`ls -d $y`;done;cd ..;done; cd ..
}

_dir=$(dirname `readlink -f $0`)
cd $_dir
echo "ezdplHome:`pwd`"

if [ -n "$1" ]; then
  #Detailed param check will be needed.
  _ipaddress=$(echo $1|awk -F':' '{print $1}')
  _port=$(echo $1|awk -F':' '{print $2}')
  if [ ${#_port} -eq 0 ]; then
    _port="22"
  fi
else
  funUsage
  exit 1
fi

if [ -n "$2" ]; then
  _server_oper=$2
else
  funUsage
  exit 1
fi

# Optional parameters
if [ -n "$3" ]; then
  _reboot=$3
else 
  _reboot="N"
fi
if [ -n "$4" ]; then
  _username=$4
else
  _username="root"
fi

# Check
echo "Target Server: ${_ipaddress}..." 
if ! ssh -p $_port $_username@$_ipaddress uname > /dev/null ; then
  echo "$_port $_username@$_ipaddress"
  echo "$_ipaddress is not reachable. "
  exit 1
fi

if [ ! -d "./servers/$_server_oper" ]; then
  echo
  echo "There is no $_server_oper configured here !"
  exit 1
fi

# Everything seems OK. Go!
echo >> ezdpl.log
echo "`date +%Y-%m-%d_%H:%M:%S` ./ezdpl $_ipaddress:$_port $_server_oper $_reboot $_username" >> ezdpl.log

# Run pre.sh on the target server
if [ -f "./servers/$_server_oper/pre.sh" ]; then
  /usr/bin/scp -q -P$_port ./servers/$_server_oper/pre.sh $_username@$_ipaddress:/tmp/
  ssh -p$_port $_username@$_ipaddress 'source /etc/profile; bash -l /tmp/pre.sh'
  _pre=$?
  if [[ $_pre != 0 ]];then 
    echo "$_username@$_ipaddress:/tmp/pre.sh exit code $_pre . EXIT!!" | tee -a ezdpl.log
    exit 1
  else
    echo "$_username@$_ipaddress:/tmp/pre.sh OK!" | tee -a ezdpl.log
  fi
fi

# Start copy app/version/files/*
if [ -d ./servers/$_server_oper/files  ]; then 
  echo -n "Start to copy ./servers/$_server_oper/files/*  "| tee -a ezdpl.log
  echo -n "......"
  if /usr/bin/scp -rq -P$_port ./servers/$_server_oper/files/* $_username@$_ipaddress:/ ; then
      echo "OK!"      | tee -a ezdpl.log
  else
      echo "Failed!"  | tee -a ezdpl.log
  fi
fi

# Run fin.sh on the target server
if [ -f "./servers/$_server_oper/fin.sh" ]; then
  /usr/bin/scp -q -P$_port ./servers/$_server_oper/fin.sh $_username@$_ipaddress:/tmp/
  ssh -p$_port $_username@$_ipaddress 'source /etc/profile; bash -l /tmp/fin.sh'
  _fin=$?
  if [[ $_fin != 0 ]];then
    echo "$_username@$_ipaddress:/tmp/fin.sh exit code $_fin . EXIT!!" | tee -a ezdpl.log
    exit 1
  else
    echo "$_username@$_ipaddress:/tmp/fin.sh OK!" | tee -a ezdpl.log
  fi
fi

# Reboot target server.
if [ "$_reboot" = "Y" ]; then
  echo
  echo "Target server will reboot..." | tee -a ezdpl.log
  echo
  ssh -p $_port $_username@$_ipaddress reboot
fi
echo "Target Server: ${_ipaddress} done!" | tee -a ezdpl.log
echo
# End of ezdpl
