alias mv='mv -i'
alias rm='rm -i'
alias cp='/bin/cp -i --preserve=timestamps'
alias df='/bin/df -hTP'
alias du='/usr/bin/du -h --max-depth=1'
alias ll='/bin/ls -lh --color=auto --time-style=long-iso 2>/dev/null'
alias lt='/bin/ls -lhtr --color=auto --time-style=long-iso 2>/dev/null'
alias mysql='mysql --default-character-set=utf8'
alias tless='less `ls -tr1|tail -1`'
alias ttail='tail -f `ls -tr1|tail -1`'
alias xscp='/usr/bin/scp -P3889 '
alias xssh='/usr/bin/ssh -p3889 '
