#!/bin/bash
_file=$1
_start=$2
_end=$3

if [[ -z $_file ]] || [[ -z $_start ]] || [[ -z $_end ]]; then
    echo "Usage: cutfile <file> <start_line#> <end_line#>"
    exit 1
fi

_file_length=`wc -l $_file |awk '{print $1}'`

if [[ $_end -gt $_file_length ]]; then
    _end=$_file_length
fi
if [[ $_start -gt $_end ]];then 
    _start=$_end
fi

_length=`echo $_end+1-$_start|bc`
head -n $_end $_file | tail -n $_length 
