#!/bin/bash
# Search dict.bing.com for words.
_param=$1
if [[ -z $_param ]]; then
   echo "Usage: dic 'word or phrase' , <file in which each word takes a line>."
   exit 1
fi

funCurlBingDic() {
   curl -sL http://cn.bing.com/dict/search?q=$1 | sed 's/\/>/\n/g'|grep '<meta name="description" content="' | sed 's/<meta name="description" content="//g' | sed 's/，/ /g' | tr -d '"' | sed 's/为您提供/ /g'| sed 's/的释义/ /g'
   # | sed 's/ /\n/g'| tr -d '"' 
}


if [[ -f $_param ]]; then
IFS="
"
    for x in `cat $_param |tr -s [:blank:] |sed 's/ /+/g' | egrep -v '(^$|^\+)'`; do
	funCurlBingDic "$x"
	echo 
    done
else
    _word=`echo "$_param" | tr -s [:blank:] | sed 's/ /+/g'`
    funCurlBingDic "$_word"
fi

