#!/bin/bash
# By panblack@126.com
# Compare files in two dirs and show the different files, including the missing ones.
_dir1=$1
_dir2=$2
_depth=$3
if [[ $# -eq 0 ]];then
    echo "Usage: filediff <dir1> <dir2> [maxdepth]"
    exit 
fi
if [[ -z $_depth ]];then
    _depth=100
fi
for x in `find "$_dir1" -maxdepth $_depth -type f | egrep -v '(.git|.svn)'`; do 
    y=${x//${_dir1}/${_dir2}}
    echo "`md5sum $x 2>/dev/null` `md5sum $y 2>/dev/null`" |awk '{if ( $1 != $3 )  print "['$_dir1'] "$2"\t['$_dir2'] "$4}'
done
